language: node_js
addons:
  apt:
    packages:
    - sshpass
node_js:
- node
install:
- npm install
script:
- npm run prod:build
after_success:
- export SSHPASS=$DEPLOY_PASS
- sshpass -e -o stricthostkeychecking=no $DEPLOY_USER@www.neospot.top 'sh ./deploy-to-vps.sh'
- sshpass -e scp  -o stricthostkeychecking=no -r ./dist/* $DEPLOY_USER@www.neospot.top:/root/runner/auth
- sshpass -e -o stricthostkeychecking=no $DEPLOY_USER@www.neospot.top 'sh ./start-vps-server.sh'
env:
  global:
  - secure: AbhtQ4pLFPlS9M51NcXRqX0p+3rJP610n0PckO1RK5FsXMSulCVdHsqCgZO6rF6CGLwUdFIjVeI6VQPD1YeARp7toFN9uk41uKgaRdKR+VlEwdMzj15EOnHq3RFedRoS9LoBD3+Eovo/uEvpNOz2gNk+DfIUt6ki96s1hNQfcrQaeXHUdtoOOl/60DHGro1DACcGhGQVrZcrh2QhGOROCaVeln5CyfiX0T0LUF06faXQADI33WJzcjVwkuuqQxZ9SQLNVM8Ky+T1iWVeH3bjTWLhhib0THxN5vTRazRUGv0PIoSCZVlljFi5zDFhb1CIZNfiT27ifAOpPVPKFUsGhFNyKk2QovHiyNC9g+C0bkJywTDKZdgfAuAeqoBRmSVfgTx4cZMBDOJxd14hDDqu+z3H1Ubhbz/7AVdTnazFJXdNjKx5zhUEEV0og6EH4rMY9GSkgXoZ60qJKJ+g462UDUS8qWkaokpNEcqpDi1gtYf7iJoFnPMxk69vUDLqiDujtAawfhF1HpFxJZZ92lt1mKPSwjsxG6CswWIVtXR2L5yL8MTkztI9Zd0/DeSEz8dtVDYaH0La8lrihk7oE3UzyW56S9UK9sGIUk4KDF5vlL5pa/V4xCQMwK2WSkFmcGe+/dJN6ubwTEEnnk7FJQkX0haMQaS9Xti+cl+InMysmG4=
  - secure: KPf2DIxQqSGKqfaEkodUjuC1Yc7uCfldEEJgg6u9GJdwI9SvV5jp3ALAZV62B/5G7/x0xJfm395tCGyL22utllssUyNCMY2dv5Rp/2n4Ghop/qNfN5d6VDW6+l2Ztv3Irw9CeWkDbagZx9fcZ2DhqoBYjunKMBWZWIANwgHAxiPk22G1oM1CTJVVh65Rpz9zruyCZ9ubqR3zhS8R/akmY01jAJB6TQ0jJij/9lATZgtfELiahUqcy8rGqC0/f4J3eQNwYl9qY4P1ThOnpANl69mBrFKwLjI6krMCntI8Bu1X71MmgFv+jicEs1G+vZlawVhE7g+UZwwJ09+o9NSFM2iOMRYWoEKWi7PHt2M+N3bXQcDYiPut1gs/Whan5gWrFYSUdyznaN3x2pn6EJi/eOtlg16Q4HG7bMstqdRTFX6PWIRf776dFyDsF1XLID/HWiFlRLwY2u2pG5FGZZamFb9wb1C3I1/JDWLTe0FqnK/zpPm/bZsmJUokzEtW0b7dUDb7HIAGDV0SJYRbZULvnfoelXWQMn/QeaBrldCWMH7u90+V/et4z+N/0WFbBWeEU88WLXTlJiI9jdWZ+L72Ld5AgnRqbTHmP3+uJKC/G5cVeEarizqw76Kt77Xsqy2nfEFwoqrRfih3TW4kcYMKKEbn2LoPTEUN0ML3ztzMwFM=
